# Generated by Django 6.0.1 on 2026-01-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gender',
            new_name='category',
        ),
    ]
